# Generated by Django 4.2.16 on 2024-11-01 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactSort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_sort_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'artifact_sort',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_desc', models.TextField()),
                ('project_sort', models.IntegerField()),
                ('project_data_sort', models.IntegerField()),
                ('artifact_selected', models.CharField(max_length=10)),
                ('banya_api_key', models.TextField()),
                ('thum_image_url', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=254)),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='ProjectDataSort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_data_sort_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'project_data_sort',
            },
        ),
        migrations.CreateModel(
            name='ProjectDetailReady',
            fields=[
                ('source', models.TextField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('artifact_sort_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'project_detail_ready',
            },
        ),
        migrations.CreateModel(
            name='ProjectSort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_sort_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'project_sort',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
